#[colors.bright]
#black = "0x6e6a86"
#blue = "0x9ccfd8"
#cyan = "0xebbcba"
#green = "0x31748f"
#magenta = "0xc4a7e7"
#red = "0xeb6f92"
#white = "0xe0def4"
#yellow = "0xf6c177"
#
#[colors.normal]
#black = "0x26233a"
#blue = "0x9ccfd8"
#cyan = "0xebbcba"
#green = "0x31748f"
#magenta = "0xc4a7e7"
#red = "0xeb6f92"
#white = "0xe0def4"
#yellow = "0xf6c177"
#
#[colors.primary]
#background = "0x191724"
#foreground = "0xe0def4"

[colors]
  [colors.primary]
    background = '0x282828'
    foreground = '0xd4be98'

  [colors.normal]
    black   = '0x3c3836'
    red     = '0xea6962'
    green   = '0xa9b665'
    yellow  = '0xd8a657'
    blue    = '0x7daea3'
    magenta = '0xd3869b'
    cyan    = '0x89b482'
    white   = '0xd4be98'

  [colors.bright]
    black   = '0x3c3836'
    red     = '0xea6962'
    green   = '0xa9b665'
    yellow  = '0xd8a657'
    blue    = '0x7daea3'
    magenta = '0xd3869b'
    cyan    = '0x89b482'
    white   = '0xd4be98'

[colors.cursor]
cursor = "0x524f67"
text = "0xe0def4"

[colors.hints.end]
background = "#1f1d2e"
foreground = "#6e6a86"

[colors.hints.start]
background = "#1f1d2e"
foreground = "#908caa"

[colors.line_indicator]
background = "None"
foreground = "None"

[colors.selection]
background = "0x403d52"
text = "0xe0def4"

[colors.vi_mode_cursor]
cursor = "0x524f67"
text = "0xe0def4"

[cursor.style]
shape = "Beam"

[cursor.vi_mode_style]
shape = "Block"

[font]
normal.family = "IosevkaTerm Nerd Font Mono"
normal.style = "Light"
size = 18

[window.dimensions]
columns = 185
lines = 50

[window.padding]
y = 0

[shell]
program = ubuntu
