require("core.plugin_config.mason")
require("core.plugin_config.lsp_config")
require("core.plugin_config.completions")
require("core.plugin_config.none-ls")
require("core.plugin_config.rose-pine")
require("core.plugin_config.lualine")
require("core.plugin_config.colorscheme")
require("core.plugin_config.nvim-tree")
require("core.plugin_config.treesitter")
require("core.plugin_config.telescope")
require("core.plugin_config.oil")
require("core.plugin_config.autopairs")
--require("core.plugin_config.rust")
--require("core.plugin_config.crates")
--require("core.plugin_config.nvim_cmp")
--require("core.plugin_config.autosession")
--require("core.plugin_config.autotag") TODO: get it from treesitter config
--require("core.plugin_config.harpoon")
--require("core.plugin_config.copilot")

